import type { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // await knex('cars').del();

  await knex('cars').insert([
    {
      title: 'Renault Clio',
      price: 500000,
      gearBox: 'manuel',
      airConditioner: true,
      fuer: 'benzin',
      doors: 4,
      seats: 5,
      distance: 45000,
    },
    {
      title: 'Toyota Corolla',
      price: 650000,
      gearBox: 'otomatik',
      airConditioner: true,
      fuer: 'dizel',
      doors: 4,
      seats: 5,
      distance: 32000,
    },
    {
      title: 'Fiat Egea',
      price: 400000,
      gearBox: 'manuel',
      airConditioner: false,
      fuer: 'benzin',
      doors: 4,
      seats: 5,
      distance: 60000,
    },
    {
      title: 'Volkswagen Golf',
      price: 750000,
      gearBox: 'otomatik',
      airConditioner: true,
      fuer: 'dizel',
      doors: 4,
      seats: 5,
      distance: 28000,
    },
    {
      title: 'Hyundai i20',
      price: 470000,
      gearBox: 'manuel',
      airConditioner: true,
      fuer: 'benzin',
      doors: 4,
      seats: 5,
      distance: 39000,
    },
    {
      title: 'Honda Civic',
      price: 800000,
      gearBox: 'otomatik',
      airConditioner: true,
      fuer: 'benzin',
      doors: 4,
      seats: 5,
      distance: 20000,
    },
    {
      title: 'BMW 3.20',
      price: 1200000,
      gearBox: 'otomatik',
      airConditioner: true,
      fuer: 'benzin',
      doors: 4,
      seats: 5,
      distance: 15000,
    },
    {
      title: 'Mercedes C200',
      price: 1400000,
      gearBox: 'otomatik',
      airConditioner: true,
      fuer: 'dizel',
      doors: 4,
      seats: 5,
      distance: 18000,
    },
    {
      title: 'Peugeot 3008',
      price: 1100000,
      gearBox: 'otomatik',
      airConditioner: true,
      fuer: 'dizel',
      doors: 4,
      seats: 5,
      distance: 25000,
    },
    {
      title: 'Ford Focus',
      price: 550000,
      gearBox: 'manuel',
      airConditioner: true,
      fuer: 'benzin',
      doors: 4,
      seats: 5,
      distance: 35000,
    },
  ]);
}
